Development
JangkarBumi/Enumerable-methods pull request #2
Opened 2019-03-22 11:25 UTC by JangkarBumi

2019-03-23 00:34 UTC, heyapricot requested changes
# Count on me 🔢
👋🏼 Hello Team! Great job building the enumerables. One little thing, the original `count` method returns the number of elements in an array if no block is given. Your version is missing that feature. Please fix and after that submit a new code review request. Thanks!

2019-03-23 01:03 UTC, JangkarBumi commented
Hi Alvaro! We are building the count method according to https://apidock.com/ruby/Array/count, I've tried to test it, I think it works just fine.

The command that I use

ary = [1, 2, 4, 2,3]
print ary.count

2019-03-25 11:37 UTC, heyapricot commented
# Good job completing the enumerables! 🔢
Hey! You've built one of your first Ruby projects! How do you feel? 
No need from my side for further review. Let's move to the next project 🚀

2019-03-25 11:37 UTC, heyapricot approved these changes

2019-03-25 11:52 UTC, merged